"""
Shared data contract for the Coach Agent output.
Owner: Coach Agent (zahra-coach)

Defines all Pydantic models that :mod:`coach` produces and that a downstream
orchestrator can consume by calling ``CoachOutput.from_json_file()``.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class TopicVerdict(str, Enum):
    """Scoring verdict assigned to each topic after the quiz."""

    UNDERSTOOD = "understood"
    NEEDS_REVIEW = "needs_review"


class QuizItem(BaseModel):
    """A single quiz question together with the developer's answer and scoring.

    Attributes:
        topic:               Short label for the concept being tested (derived
                             from the session log question).
        question:            The quiz question generated by the Coach.
        expected_keywords:   Key concepts the correct answer must address.
        developer_answer:    The answer submitted by the developer (empty string
                             if no answer was provided).
        verdict:             ``"understood"`` or ``"needs_review"``, assigned
                             after scoring.
    """

    topic: str = Field(..., description="Short label for the concept being tested")
    question: str = Field(..., description="Quiz question generated by the Coach")
    expected_keywords: list[str] = Field(
        default_factory=list,
        description="Keywords/concepts the correct answer must address",
    )
    developer_answer: str = Field(
        default="",
        description="Developer's submitted answer; empty string if not provided",
    )
    verdict: TopicVerdict = Field(
        default=TopicVerdict.NEEDS_REVIEW,
        description="'understood' or 'needs_review' assigned after scoring",
    )

    model_config = {"use_enum_values": True}


class TaskRecommendation(BaseModel):
    """A single starter task recommended to the developer.

    Attributes:
        file:    Repo-relative file path (from ``MapperOutput.entry_points``).
        reason:  One sentence explaining why this file fits the developer's
                 current understanding, derived from the Mapper's classification
                 ``reason`` field and the quiz verdicts.
    """

    file: str = Field(..., description="Repo-relative path from MapperOutput.entry_points")
    reason: str = Field(
        ...,
        description=(
            "One-sentence explanation of why this file matches the developer's "
            "demonstrated understanding"
        ),
    )


class CoachOutput(BaseModel):
    """The complete output of one Coach session.

    Produced by :func:`coach.run_coach_session` and written to
    ``coach_output.json`` via :meth:`to_json_file`.

    Attributes:
        generated_at:        UTC timestamp of generation.
        repo_root:           Absolute repo root path, passed through from
                             ``MapperOutput.repo_root``.
        quiz:                The three quiz items, each with its verdict.
        topic_scores:        Mapping of topic label → verdict string
                             (``"understood"`` or ``"needs_review"``).
                             Derived directly from ``quiz`` for convenience.
        recommended_task:    The one starter task recommended to the developer.
                             ``None`` when no suitable entry point is available.
        error:               Non-empty only when the Coach encountered an
                             unrecoverable condition (e.g. empty session log).
                             When set, all other fields may be empty/None.
    """

    generated_at: datetime = Field(default_factory=datetime.utcnow)
    repo_root: str = Field(default="", description="Repo root from MapperOutput")
    quiz: list[QuizItem] = Field(
        default_factory=list,
        description="Three quiz items with questions, answers, and verdicts",
    )
    topic_scores: dict[str, str] = Field(
        default_factory=dict,
        description="topic label → 'understood' | 'needs_review'",
    )
    recommended_task: Optional[TaskRecommendation] = Field(
        default=None,
        description="Single starter task matched to the developer's strengths",
    )
    error: str = Field(
        default="",
        description="Human-readable error message; empty when the run succeeded",
    )

    model_config = {"use_enum_values": True}

    def to_json_file(self, path: str) -> None:
        """Serialise this object to a JSON file at *path*."""
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(self.model_dump_json(indent=2))

    @classmethod
    def from_json_file(cls, path: str) -> "CoachOutput":
        """Deserialise a ``CoachOutput`` from a JSON file at *path*."""
        with open(path, "r", encoding="utf-8") as fh:
            return cls.model_validate_json(fh.read())
